remote_theme: epidrome/cover-card@main

title: 'Бобры. Загородные дома'
description: 'Подписывайтесь на наши соц сети, чтобы быть в курсе'

avatar: 'БОБРЫПНГ.png'
background: 'background.jpg'
favicon: 'БОБРЫПНГ.png'

instagram: 'bobry_country_houses'
vk: 'bobryhouses'
max: 'f9LHodD0cOJPFlIMvgwL6YRxq3bvho5sFw8tnhwZDB45g3SDnXQybzzWfxA'
telegram: 'bobryhouses'
whatsapp: '79214060607'
website: ''
living: 'rules'
reviews: '169139949040/reviews'
call: '+79214060607'
book: 'gDleLbdhMC'

social-links-order: [website, reviews, whatsapp, telegram, vk, max, instagram, living, call, book]

social-links:
  - name: vk
    url-pattern: ://vk.com__
  - name: instagram
    url-pattern: ://instagram.com__
  - name: whatsapp
    url-pattern: wa.me/__USERNAME__
  - name: telegram
    url-pattern: telegram.me/__USERNAME__
  - name: website
    url-pattern: www.bobryhouses.ru/__USERNAME__
    icon-class: fab fa-2x fa-chrome
  - name: living
    url-pattern: www.bobryhouses.ru/__USERNAME__
    icon-class: fas fa-2x fa-house-user
  - name: reviews
    url-pattern: yandex.ru/maps/org/bobry_country_houses/__USERNAME__
    icon-class: fas fa-2x fa-comments
  - name: call
    url-scheme: 'tel:'
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-phone
  - name: book
    url-pattern: homereserve.ru/__USERNAME__
    icon-class: fas fa-2x fa-calendar-alt
  - name: max
    url-pattern: max.ru/u/__USERNAME__
    icon-class: fas fa-2x fa-comment-dots
