# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Бобры. Загородные дома'
description: 'Подписывайтесь на наши соц сети, чтобы быть в курсе'

# Images
avatar: 'БОБРЫПНГ.png'
background: 'background.jpg'
favicon: 'БОБРЫПНГ.png'

# Online profiles
#dribbble: 'mydribbble'
#facebook: 'myfacebook'
#twitter: 'mytwitter'
#linkedin: 'mylinkedin'
instagram: 'bobry_country_houses'
#pinterest: 'mypinterest'
#youtube: 'myyoutube'
#github-user: 'mygithub'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#rubygems: ''
#medium:  ''
#tumblr: 'mytumblr'
#weibo: 'myweibo'
vk: 'bobryhouses'
max: 'f9LHodD0cOJPFlIMvgwL6YRxq3bvho5sFw8tnhwZDB45g3SDnXQybzzWfxA'
telegram: 'bobryhouses'
whatsapp: '79214060607'
#blog_url: 'myblog.blog.com'
#email: 'hello@example.com'
#messenger: 'myfbchat'
website: ''
проживание: 'rules'
отзывы: '169139949040/reviews'
позвонить: '+79214060607'
забронировать: 'gDleLbdhMC'

social-links-order: [website, отзывы, whatsapp, telegram, vk, max, instagram, проживание, позвонить, забронировать]

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: twitter
    url-pattern: twitter.com/__USERNAME__

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: google-plus
    url-pattern: plus.google.com/+__USERNAME__

  - name: vk
    url-pattern: vk.com/__USERNAME__

  - name: weibo
    url-pattern: weibo.com/__USERNAME__

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: flickr
    url-pattern: flickr.com/__USERNAME__

  - name: pinterest
    url-pattern: pinterest.com/__USERNAME__

  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: gitlab-user
    url-pattern: gitlab.com/__USERNAME__
    icon-class: fab fa-2x fa-gitlab

  - name: whatsapp
    url-pattern: wa.me/__USERNAME__

  - name: codepen
    url-pattern: codepen.com/__USERNAME__

  - name: stack-overflow
    url-pattern: stackoverflow.com/users/__USERNAME__

  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__

  - name: rubygems
    url-pattern: rubygems.org/profiles/__USERNAME__
    icon-class: far fa-2x fa-gem

  - name: steam
    url-pattern: steamcommunity.com/id/__USERNAME__

  - name: youtube
    url-pattern: youtube.com/__USERNAME__

  - name: vimeo
    url-pattern: vimeo.com/__USERNAME__

  - name: soundcloud
    url-pattern: soundcloud.com/__USERNAME__

  - name: lastfm
    url-pattern: last.fm/user/__USERNAME__

  - name: medium
    url-pattern: medium.com/@__USERNAME__

  - name: tumblr
    url-pattern: __USERNAME__.tumblr.com

  - name: dribbble
    url-pattern: dribbble.com/__USERNAME__

  - name: keybase
    url-pattern: keybase.io/__USERNAME__

  - name: messenger
    url-pattern: m.me/__USERNAME__
    icon-class: fab fa-2x fa-facebook-messenger

  - name: telegram
    url-pattern: telegram.me/__USERNAME__

  - name: snapchat
    url-pattern: snapchat.com/add/__USERNAME__

  - name: quora
    url-pattern: www.quora.com/profile/__USERNAME__

  - name: blog_url
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-blog

  - name: website
    url-pattern: www.bobryhouses.ru/__USERNAME__
    icon-class: fa fa-2x fa-chrome

  - name: проживание
    url-pattern: www.bobryhouses.ru/__USERNAME__
    icon-class: fa fa-2x fa-house-user

  - name: отзывы
    url-pattern: yandex.ru/maps/org/bobry_country_houses/__USERNAME__
    icon-class: fas fa-2x fa-comments
    
  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open

  - name: позвонить
    url-scheme: 'tel:'
    url-pattern: '__USERNAME__'
    icon-class: fa fa-2x fa-phone

  - name: забронировать
    url-pattern: homereserve.ru/__USERNAME__
    icon-class: fas fa-2x fa-calendar-alt

   - name: max
    url-pattern: max.ru/u/__USERNAME__
    icon-class: fas fa-2x fa-comment-dots
